package Main;

import Enum.enTipVlasnistva;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author m.jakas
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoVozilo = new javax.swing.JLabel();
        btnDodajVozilo = new javax.swing.JButton();
        txtRegistracija = new javax.swing.JTextField();
        cbTipVozila = new javax.swing.JComboBox<>();
        lblNovoVozilo1 = new javax.swing.JLabel();
        cbNamenaVozila = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNovoVozilo.setText("Tip Vozila");

        btnDodajVozilo.setText("Dodaj vozilo");
        btnDodajVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajVoziloActionPerformed(evt);
            }
        });

        txtRegistracija.setText("BG256-OL");

        cbTipVozila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "motocikl", "automobil", "kamion" }));

        lblNovoVozilo1.setText("Namena Vozila");

        cbNamenaVozila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Privatno,", "Sluzbeno,", "Vojno,", "JavniPrevoz   " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDodajVozilo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNovoVozilo)
                        .addGap(18, 18, 18)
                        .addComponent(cbTipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblNovoVozilo1)
                        .addGap(18, 18, 18)
                        .addComponent(cbNamenaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNovoVozilo1)
                        .addComponent(cbNamenaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNovoVozilo)
                        .addComponent(cbTipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajVozilo)
                    .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajVoziloActionPerformed
        // TODO add your handling code here:
        try
        {
            if(pj == null)
            {
                pj = new ProjectJanuar();
            }
            boolean res;
            res = pj.addVozilo(cbTipVozila.getSelectedItem().toString(),enTipVlasnistva.Privatno,"Audi", cbNamenaVozila.getSelectedItem().toString(),"BG258-OL","Dijana","Jakas","b.Arsenija Carnojevica 137");
            if(res==true)
            {
                JOptionPane.showMessageDialog(this, "Uspesno dodano vozilo! " );
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Vozilo nije dodano " );
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Greska: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDodajVoziloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    //region variables
    private ProjectJanuar pj;
    //endregion

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajVozilo;
    private javax.swing.JComboBox<String> cbNamenaVozila;
    private javax.swing.JComboBox<String> cbTipVozila;
    private javax.swing.JLabel lblNovoVozilo;
    private javax.swing.JLabel lblNovoVozilo1;
    private javax.swing.JTextField txtRegistracija;
    // End of variables declaration//GEN-END:variables
}
